### ISSUE TITLE
Copy needs an edit

### ISSUE THREAD

**Issue by canuckjacq** [HackForEquality/YesEquality#3]
This is for me to do. Just a reminder.

**Comment by canuckjacq** [comment]
The coloured overlays are the wrong ones. Use the ones that are transparencies like the white ones. They should be in the slack group or I have them by email if not.

**Comment by Lmd64-zz** [comment]
canuckjack copy updates:
- The first info page should go. The copy is problematic and preachy. All the other pages are useful. 
- “Registered to Vote” should have a small v on vote. 
- “Download the Form” small f on form
- Unsure on this — is Garda a proper noun? Probably a small g here, but I am happy to be corrected (Liam: it's a proper noun, so I reckon a 'G' is warranted!)

**Comment by colmdoyle** [comment]
So comments from the campaign -

On the swipe screens...
·         Can we keep 1 – 7 unchanged.
·         On screen 8 (postbox) can we change the text below the icon to “Return it to your local authority office by May 5th.”
·         Screen 9 (vote envelope) – Text above the icon “On May 22nd” text below “Polling stations will be open from 7am to 10pm.”
·         Delete screen 10 and 11 (away for work && change of address)
·         Screen 13.. can we include a link to www.yesequality.ie at the bottom

**Comment by canuckjacq** [comment]
Also -- Registered To vote should have a small t in "to", only noticed that one today :)

**Comment by adam-govan** [comment]
Most of these corrects are already present. The "To" was made into a "to" on the Registered to vote Screen. 

The Yes Equality icon goes to the website? do we still need a hyperlink?
