### ISSUE TITLE
After taking a photo, no share options

### ISSUE THREAD

**Issue by canuckjacq** [HackForEquality/YesEquality#9]
It takes the photo and then there's no share. 

iPhone 5 8.3 (testflight)

**Comment by Lmd64-zz** [comment]
What device did that occur on?

**Comment by canuckjacq** [comment]
Sorry, I thought I'd noted that. IPhone 5, 8.3

**Comment by canuckjacq** [comment]
Ok, it appears this happens if you press the info or reminders buttons after you take the photo, before sharing.

**Comment by adam-govan** [comment]
It's just resetting the Share button when it goes out of the view. The ViewWillAppear was doing that. 

replaced :    [self shouldShowShareButton:NO animated:NO];
with:    [self shouldShowShareButton:self.isDisplayingStillImage animated:NO];

Seems to do the trick ;) 

pushing to bug-fixes
